### ISSUE TITLE
About the Spinal cord grey matter segmentation challenge dataloader 

### ISSUE THREAD

**Issue by Lkiku** [vios-s/vMFNet#1]
Hi! 
I noticed that you only released the M&Ms dataloader in this repo. I downloaded two dataset and I found that the SCGM dataset is much smaller. So I think it is easier to reproduce since I don't have too much GPU resources. Could you also make the SCGM dataloader available?

**Comment by xxxliu95** [comment]
Hi, thanks for your interest, we did not manage to release that part of the code. 

You can find one data loader for SCGM here: https://github.com/wyf0912/LDDG/blob/master/dataset/spinal_cord_challenge.py

It might not be well aligned with my code. But it is not hard to build the data loader based on that for vMFNet.

Best wishes,
Xiao

**Comment by Lkiku** [comment]
> 
Thanks a lot!
